import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import { useThemeStore } from "@/store/useThemeStore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  // const { theme } = useThemeStore();

  return (
    <html lang="en" data-theme={theme}>
      <body>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
